### ISSUE TITLE
Resizing figures

### ISSUE THREAD

**Issue by JasonSqz** [jtr13/edav2#7]
I resized all the graphs in chapter 3.
Basically I am using the chunk option following:
-base size: `fig.width=4, fig.height=3`
-median: 1.2x base size
-large: 1.5x base size

Some of the figures do not follow as I think they look better using some other sizes.

- [x]  Also, I noticed that the link to EDAV 1.0 actually points to EDAV 2.0 on the index page.

Also added additional resources section for boxplot.

**Comment by jtr13** [comment]
The figure sizes look great! I also like the the descriptive titles on the graphs which make it very clear what each is showing.

The `Orange` dataset unfortunately is not a good choice for boxplots since all of the values in each boxplot represent a measurement of the same tree over time, rather than, say, a distribution of a measurement of different trees all of the same type. (Sorry I missed this earlier.) A better choice is the `chickwts` dataset used in the 1st ed. You can leave out the "Casein Makes You Fat?!" title. 

In terms of the link, are you referring to the one on this page: https://edav.info/index.html ? When I click on it, it takes me to the first edition.  Is that not working for you?

**Comment by JasonSqz** [comment]
I think it's just a problem with the browser cache or something, it directs to the first edition when I am using my pc :)
We will change the boxplot example.
